services:
  redis-server:
    image: redis
    container_name: redis-server
    ports:
      - '6379:6379'
    volumes:
      - ./redis-service/config/redis.conf:/redis.conf
    command: ['redis-server', '/redis.conf']

  otpwa:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: kodingworks/otpwa:latest
    environment:
      - TZ=${TZ}
      - PORT=${PORT}
      - DB_URL=${DB_URL}
      - DB_NAME=${DB_NAME}
      - REDIS_TTL=${REDIS_TTL}
      - ENCRYPTION_ALGORITHM=${ENCRYPTION_ALGORITHM}
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
      - TOKEN=${TOKEN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - '3000:3000' # expose-to-the-world : only-in-the-docker
    container_name: otpwa
    # depends_on:
    # -
    volumes:
      - ./:/otpwa
      - ./:/node_modules

volumes:
  redis-data:
