version: '3.3'
services:
  redis-server:
    image: redis
    container_name: redis-server
    ports:
      - '6380:6380'
    volumes:
      - ./redis-service/config/redis.conf:/redis.conf
    command: --port 6380
    expose:
      - '6380'
  #    command: ['redis-server', '/redis.conf']

  otpwa:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: kodingworks/otpwa:latest
    environment:
      - TZ=${TZ}
      - PORT=${PORT}
      - ENCRYPTION_ALGORITHM=sha256
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
      - TOKEN=${TOKEN}
      - REDIS_TTL=604800 # Default 7 Days
      - REDIS_HOST=redis-server
      - REDIS_PORT=6380
    ports:
      - '4125:4125' # expose-to-the-world : only-in-the-docker
    container_name: otpwa
    # depends_on:
    # -
    volumes:
      - ./:/otpwa
      - ./:/node_modules

volumes:
  redis-data:
